In [1]:
import os
import sys
import dimod
import matplotlib.pyplot as plt
import numpy as np

this_folder = os.path.dirname(os.path.abspath(os.getcwd()))
sys.path.insert(0, this_folder)

from utils import *
from optimized_qubos import *

dim = 2
initial_tensor = get_standard_tensor(dim) #% 2
suggested_optimal = 7 #Proved optimal for multiplying 2x2 matrices
origo = np.tensordot([0]*4, np.tensordot([0]*4, [0]*4, axes=0), axes=0)

In [2]:
strassen_tensors_np = [np.tensordot([0,0,0,1], np.tensordot([-1,0,1,0], [1,0,1,0], axes=0), axes=0),
           np.tensordot([1,1,0,0], np.tensordot([0,0,0,1], [-1,1,0,0], axes=0), axes=0),
           np.tensordot([-1,0,1,0], np.tensordot([1,1,0,0], [0,0,0,1], axes=0), axes=0),
           np.tensordot([1,0,0,1], np.tensordot([1,0,0,1], [1,0,0,1], axes=0), axes=0),
           np.tensordot([0,1,0,-1], np.tensordot([0,0,1,1], [1,0,0,0], axes=0), axes=0),
           np.tensordot([1,0,0,0], np.tensordot([0,1,0,-1], [0,1,0,1], axes=0), axes=0),
           np.tensordot([0,0,1,1], np.tensordot([1,0,0,0], [0,0,1,-1], axes=0), axes=0)]

In [3]:
def construct_all_tensors(sample, dim):
    positive_linear_vars = []
    tensors = []
    for i in range(suggested_optimal):
        x, y, z = [], [], []
        for j in range(dim**2):
            x.append(sample[str(i) + "x" + str(j)])
            y.append(sample[str(i) + "y" + str(j)])
            z.append(sample[str(i) + "z" + str(j)])
        tensors.append([x,y,z])
    return tensors

In [4]:
weight = 10
initial_tensor = get_standard_tensor(dim)
bqm, hubo, aux_ids = towards_user_defined_full(initial_tensor, dim, suggested_optimal, weight)

print("Number of linear variables: ", len(bqm.linear))
print("Number of quadratic variables: ", len(bqm.quadratic))

sample, energy, sampleset = solve_bqm_in_leap(bqm, "LeapHybrid")

tensors = construct_all_tensors(sample, dim)

initial_tensor = get_standard_tensor(dim)
for t in tensors:
    initial_tensor = np.mod(initial_tensor - np.tensordot(t[0], np.tensordot(t[1], t[2], axes=0), axes=0), 2)
    
if np.count_nonzero(initial_tensor.flatten()) == 0:
    print("Success!")
else:
    print("No success")
    
print(tensors)
print(initial_tensor)

Number of linear variables:  717
Number of quadratic variables:  3467
Energy:  17.0
No success
[[[1, 0, 1, 0], [0, 1, 0, 0], [0, 0, 1, 0]], [[0, 1, 0, 0], [0, 1, 0, 0], [1, 0, 0, 0]], [[1, 0, 0, 1], [1, 1, 0, 0], [0, 0, 0, 1]], [[0, 0, 0, 0], [1, 0, 1, 0], [0, 1, 0, 0]], [[0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]], [[0, 1, 1, 0], [0, 0, 1, 1], [1, 0, 0, 0]], [[1, 0, 1, 1], [0, 1, 0, 0], [0, 1, 1, 0]]]
[[[1. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 1. 1.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]


The following line shows that the quantum annealer did not find the optimal point because we can construct a point with lower energy.

In [5]:
bqm.energy(get_test_strassen_test_tensor(bqm, aux_ids))

0.0