In [1]:
import dimod
from dimod.generators.constraints import combinations
from dwave.system import LeapHybridSampler
from hybrid.reference import KerberosSampler

import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)

from numpy.random import shuffle
import json
import csv
import itertools
import os
import math
import random
import matplotlib.pyplot as plt

from utils import *
from qubos import *

notebook_path = os.path.abspath("main.ipynb")

In [2]:
#print(initial)

In [3]:
def search_matrix_multiplication(initial_tensor, target_tensor, iteration_limit, file_name, dim):
    tensor = initial_tensor
    file = open("results//" + file_name + ".txt", "w")
    file.write(str(initial_tensor) + "\n")
    file.close()
    for k in ["x","y","z"]:
        for j in range(dim**2):
            term = k + str(j)
            tensor = initial_tensor
            print("----------------------------------------------")
            print(term)
            vectors = []
            for i in range(iteration_limit):
                bqm = towards_user_defined(tensor, target_tensor, dim)
                #v = construct_point_for_energy_evaluation(tensor, x, y, z, dim)
                #print(bqm.energy(v))
                if i == 0:
                    bqm.fix_variable(term, 1)
                sample, energy = solve_bqm_in_leap(bqm, sampler = "Greedy") #LeapHybrid
                if i == 0:
                    sample[term] = 1
                print_solution(sample)
                x, y, z = process_result(sample, dim)
                print(x, y, z)
                if energy in vectors:
                    break
                vectors.append(energy)
                if len(x) + len(y) + len(z) == 0:
                    break


                tensor = (tensor - np.tensordot(x, np.tensordot(y, z, axes=0), axes=0)) % 2
                file = open("results//" + file_name + ".txt", "a")
                file.write(str(x) + " " + str(y) + " " + str(z) + "\n")
                file.write(str(tensor) + "\n")
                file.close()
                if np.array_equal(tensor, target_tensor):
                    print("Algorithm reached the target.")
                    print(term)
                    break

In [4]:
target_tensor = np.load("3x3_target_tensor.npy")
vectors = [
    [[0, 0, 0, 0, 0, 1, 0, 1, 1], [0, 1, 0, 0, 1, 1, 0, 1, 0], [0, 0, 0, 1, 1, 0, 0, 0, 1]], 
    [[1, 0, 1, 0, 0, 0, 1, 0, 0], [1, 0, 1, 1, 0, 0, 1, 0, 0], [1, 0, 1, 0, 0, 0, 1, 0, 0]], 
    [[0, 1, 1, 0, 1, 0, 0, 0, 0], [1, 0, 1, 0, 0, 0, 1, 0, 1], [0, 1, 0, 1, 0, 0, 1, 0, 0]]]
#initial = np.zeros((9,9,9))
#for v in vectors:
#    target_tensor = (target_tensor - np.tensordot(v[0], np.tensordot(v[1], v[2], axes=0), axes=0)) % 2

#print(target_tensor)
search_matrix_multiplication(np.zeros((9,9,9)), target_tensor, 50, "3x3_uphill", 3)

----------------------------------------------
x0
Energy:  295.0
z3 1
z4 1
z8 1
y4 1
y7 1
y5 1
x5 1
y1 1
x7 1
x8 1
x0 1
Error:  4
[1 0 0 0 0 1 0 1 1] [0 1 0 0 1 1 0 1 0] [0 0 0 1 1 0 0 0 1]
Energy:  222.0
z0 1
x0 1
y0 1
z2 1
z6 1
y2 1
y3 1
y6 1
x2 1
x6 1
Error:  0
[1 0 1 0 0 0 1 0 0] [1 0 1 1 0 0 1 0 0] [1 0 1 0 0 0 1 0 0]
Energy:  175.0
y0 1
z1 1
z3 1
z6 1
y2 1
x1 1
x4 1
Error:  0
[0 1 0 0 1 0 0 0 0] [1 0 1 0 0 0 0 0 0] [0 1 0 1 0 0 1 0 0]
Energy:  159.0
Error:  0
[] [] []
----------------------------------------------
x1
Energy:  296.0
z3 1
z4 1
z8 1
y4 1
y7 1
y5 1
x5 1
y1 1
x7 1
x8 1
x1 1
Error:  4
[0 1 0 0 0 1 0 1 1] [0 1 0 0 1 1 0 1 0] [0 0 0 1 1 0 0 0 1]
Energy:  218.0
z0 1
x0 1
y0 1
z2 1
z6 1
y2 1
y3 1
y6 1
x2 1
x6 1
Error:  0
[1 0 1 0 0 0 1 0 0] [1 0 1 1 0 0 1 0 0] [1 0 1 0 0 0 1 0 0]
Energy:  195.0
Error:  0
[] [] []
----------------------------------------------
x2
Energy:  302.0
z0 1
x0 1
y0 1
z2 1
z6 1
y2 1
y3 1
y6 1
x6 1
x2 1
Error:  0
[1 0 1 0 0 0 1 0 0] [1 0 1 1 0 0 1 0 